# Generated by Django 3.1.7 on 2021-06-02 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210512_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 20, 28, 44, 949935), verbose_name='date published'),
        ),
    ]
